### ISSUE TITLE
lack of some head files?

### ISSUE THREAD

**Issue by 01joy** [mhoopmann/kojak#2]
Hi, I can't find some head files, such as `MSReader.h`, `pepXMLWriter.h` which are used in [line25,26](https://github.com/mhoopmann/kojak/blob/master/KData.h#L25).

Could you please provide the whole project with me? 

Thanks.

**Comment by mhoopmann** [comment]
Sure thing. The supporting file reading library is at: 
https://github.com/mhoopmann/MSToolkit

Cheers,
Mike

**Comment by 01joy** [comment]
Oh, I see, Thanks.

BTW, I want to know does Kojak support mgf as ms2?

**Comment by mhoopmann** [comment]
Kojak will accept MGF as a file format, but I'm getting unreliable behavior due to the lack of precursor information. I will have to work on a more permanent solution.

**Comment by mhoopmann** [comment]
The MGF support has been greatly improved. Precursor information is no longer necessary by setting precursor_refinement=0
