### ISSUE TITLE
How to set peptide variable modification?

### ISSUE THREAD

**Issue by fcyu** [mhoopmann/kojak#3]
Hi,

Is "@" and "$" indicate peptide N-terminal and C-terminal, respectively? I tried, but it looks like not working.

Thanks

**Comment by mhoopmann** [comment]
Hi fcyu,
You are right that the functionality isn't working - I've forgotten to update the documentation. Right now, modifications are restricted to protein N-terminus and protein C-terminus with 'c' and 'n'.

I will correct this to restore functionality for variable peptide modifications to the termini.
Best,
Mike

**Comment by fcyu** [comment]
Hi Mike,

Thanks for your reply. One more question: Do you have a plan to add peptide terminal variable modification back?

Thanks

**Comment by mhoopmann** [comment]
Yes, I do plan it for the next release. Perhaps later this week.
Cheers,
Mike

**Comment by fcyu** [comment]
Great! Then I will wait for the next release.

Thanks

**Comment by mhoopmann** [comment]
The new release has been posted on the Kojak website. A detailed description is at: http://www.kojak-ms.org/news/index.html

Downloads found at: http://www.kojak-ms.org/download.html
