### ISSUE TITLE
Got segmentation fault while running on some dataset

### ISSUE THREAD

**Issue by shawn-peng** [mhoopmann/kojak#6]
Hi,

I just start running some searches but I'm stuck with segmentation faults with several searches. I'm running with Release2.0.0alpha1. Could I get some help? Here is an example config and data file.

https://drive.google.com/drive/folders/1TYIF0IySubVOH4aFzeaKjwtVqzjJsziB?usp=sharing

Thanks,
Yisu

**Comment by mhoopmann** [comment]
Hi Yisu,
Sorry for the problem, but thank you for sending the example. It was certainly helpful. I believe the issue is that you have MS1_centroid=0 in your parameters, but your data are centroided. Try setting MS1_centroid=1 and rerun Kojak.

Kojak does have a new warning system that is supposed to catch these mistakes, but it obviously has a bug because you did not get any such report. I'll fix this for the next release. Thanks for posting the problem!

Cheers,
Mike

**Comment by shawn-peng** [comment]
Hi Mike,
Thank you so much for your reply. I've tried the new setting but I'm still getting the segmentation fault.

Here is the log that I get.

> Kojak version 2.0.0 alpha 2, December 20 2019
> Copyright Michael Hoopmann, Institute for Systems Biology
> Visit http://kojak-ms.org for full documentation.
> 
> ****** Begin Kojak Analysis ******
>  Time at start: Fri Oct 16 16:39:16 2020
> 
>  Parameter file: ecoli_xl_kojak.conf
> WARNING: Parameter percolator_filehas been deprecated and will be ignored.
> 
>  Reading FASTA database: /home/yisupeng/workspace/xlms/db/uniprot-proteome_UP000000625.fasta
> WARNING: sp|P58095|YPJI_ECOLI Putative UPF0401 protein YpjI OS=Escherichia coli (strain K12) OX=83333 GN=ypjI PE=5 SV=1 has an unexpected amino acid character or errant white space: 'X'
> WARNING: Mass of 'X' is currently set to 0. Consider revising with the aa_mass parameter.
> WARNING: sp|P58095|YPJI_ECOLI Putative UPF0401 protein YpjI OS=Escherichia coli (strain K12) OX=83333 GN=ypjI PE=5 SV=1 has an unexpected amino acid character or errant white space: 'X'
> WARNING: Mass of 'X' is currently set to 0. Consider revising with the aa_mass parameter.
> WARNING: sp|P76000|YCGI_ECOLI Putative uncharacterized protein YcgI OS=Escherichia coli (strain K12) OX=83333 GN=ycgI PE=5 SV=2 has an unexpected amino acid character or errant white space: 'X'
> WARNING: Mass of 'X' is currently set to 0. Consider revising with the aa_mass parameter.
> WARNING: sp|P39901|YBFI_ECOLI Putative uncharacterized protein YbfI OS=Escherichia coli (strain K12) OX=83333 GN=ybfI PE=5 SV=1 has an unexpected amino acid character or errant white space: 'X'
> WARNING: Mass of 'X' is currently set to 0. Consider revising with the aa_mass parameter.
> WARNING: sp|P75901|EFEU_ECOLI Putative inactive ferrous iron permease EfeU OS=Escherichia coli (strain K12) OX=83333 GN=efeU PE=5 SV=2 has an unexpected amino acid character or errant white space: 'X'
> WARNING: Mass of 'X' is currently set to 0. Consider revising with the aa_mass parameter.
> WARNING: sp|P45766|YHDW_ECOLI Putative amino-acid ABC transporter-binding protein YhdW OS=Escherichia coli (strain K12) OX=83333 GN=yhdW PE=1 SV=2 has an unexpected amino acid character or errant white space: 'X'
> WARNING: Mass of 'X' is currently set to 0. Consider revising with the aa_mass parameter.
> WARNING: sp|P37003|YBFG_ECOLI Putative uncharacterized protein YbfG OS=Escherichia coli (strain K12) OX=83333 GN=ybfG PE=5 SV=3 has an unexpected amino acid character or errant white space: 'X'
> WARNING: Mass of 'X' is currently set to 0. Consider revising with the aa_mass parameter.
> WARNING: sp|P33369|MDTQ_ECOLI Putative multidrug resistance outer membrane protein MdtQ OS=Escherichia coli (strain K12) OX=83333 GN=mdtQ PE=5 SV=2 has an unexpected amino acid character or errant white space: 'X'
> WARNING: Mass of 'X' is currently set to 0. Consider revising with the aa_mass parameter.
>   Total Proteins: 4391
>   Adding Kojak-generated decoys. New Total Proteins: 8782
>   650288 peptides to search (305499 linkable).
> 
>  Reading spectra data file: spec/xl/ecoli_xl/DESTRibo_092010exp2_LEF4.mzML ... 100%
>   1425 total spectra have enough data points (12 peaks) for searching.
>   Mapping precursors ... 100%
>   1425 spectra with 76706 peaks will be analyzed.
>   Using Kojak modified XCorr scores.
>   Transforming spectra ... 100%
> 
>  Start spectral search: Fri Oct 16 16:39:22 2020
>   Scoring peptides ... 100%
>   Second pass ... 100%
>   Calculating e-values (5000)... 61%

Best,
Yisu
